### ISSUE TITLE
本地代理端口被占用时无提醒

### ISSUE THREAD

**Issue by Snapmali** [xxzl0130/CodeX#10]
目前本地代理8080或8081端口被占用时GF_Tool_Server.exe会直接报错退出，而GUI并不会提示错误信息。
![image](https://user-images.githubusercontent.com/34858368/164717147-9ef3000d-a0ea-4d67-adfe-092a2beac1c8.png)
![image](https://user-images.githubusercontent.com/34858368/164717224-9e7f9998-9e79-414e-b9db-be83359a62c0.png)

建议在端口被占用时弹出提醒，并使用随机端口或允许用户自定义本地代理端口。

**Comment by xxzl0130** [comment]
之前本来是改了这里，估计是某次把GF_Tool_Server.exe换错了
