### ISSUE TITLE
日版支持

### ISSUE THREAD

**Issue by sky7st** [xxzl0130/CodeX#2]
日服下禮拜就要開重裝了

我先稍微看了一下日版
幫你整理了一下日版的API的部分 希望能讓 GF_Tool_Server.exe 支援日版 
或是開源給我我應該也能改XD

1.日版跟陸版一樣都採用HTTP

2. host名稱 
ppgame.com
對應日版:
gfjp-game.sunborngame.com

3.陸版 API: 
/Index/getDigitalSkyNbUid
對應日版:
/Index/getUidEnMicaQueue

4陸版API:
/Index/index
對應日版:
不變

5.cipher:  加密方式不變

6.近期有打算把codeX UI語言改為能選擇簡/繁中/日文版

**Comment by xxzl0130** [comment]
GF_Tool_Server也是开源的，你可以在我的库里找到，不过应该是可以直接用于日服的。  UI语言方面，如果能提供翻译，我很乐意更新。  最后，重装如果是刚开，也不急着用计算器啊，到5星还要很久。

**Comment by xxzl0130** [comment]
经过测试，GF_Tool_Server可直接用于日版。  
翻译的问题，由于Qt的ui系统的一些问题，暂时搁置。  
~~反正也不是看不懂~~
