### ISSUE TITLE
"禁止用于商业" in README.md contradicts LICENSE (LGPLv3).

### ISSUE THREAD

**Issue by johnchen902** [xxzl0130/CodeX#3]
According to README.md, this work "禁止用于商业". (To non-Chinese speakers: "禁止用于商业" means "no commercial use.")

However, according to LICENSE, this work is licensed under GNU Lesser General Public License version 3.

> If the Program as you received it, or any part of it, contains a notice stating that it is governed by this License along with a term that is a further restriction, you may remove that term.

Therefore, "禁止用于商业", a term being a "further restriction", has no effect.

**Comment by xxzl0130** [comment]
The term here is just used to avoid potential warning or lawsuit from the production team, not for opensource.  
But still thanks for notice, I'll check the license later.
