### ISSUE TITLE
关于设置保存

### ISSUE THREAD

**Issue by dongshunyao** [xxzl0130/CodeX#4]
希望作者能提供 设置界面设置内容的本地保存 的支持。

~~作者不想写的话要不我自己写一个然后提 PR ？~~

**Comment by xxzl0130** [comment]
重装格数配置这部分应该绝大多数人都会使用默认的最优解，没有什么额外保存的必要。  
至于求解数量，也不是啥很重要的东西。这个我会在下次更新的时候附带上。  
当然你想写代码也欢迎PR。

**Comment by dongshunyao** [comment]
感谢回复！

功能挺完善暂时也没啥想PR的，蹲一波后续更新~

已支持XD
