### ISSUE TITLE
怎么改都显示没解？

### ISSUE THREAD

**Issue by gao462** [xxzl0130/CodeX#5]
日服玩家，不太懂重装芯片的玩法。我现在能提取芯片数据，但是不管我怎么改重装部队的设置，永远显示没有解。
以AGS30为例，开代理，然后提取，显示有大约110个锁定的芯片（没有部队装备），我勾选了使用已锁定，其他的都没选，把设置里面AGS30的每一项都设成0了（其他还是默认值），然后点计算，显示没有解。
我不知道是不是理解错了，这个解应该是指不低于设置值的一种拼法吧？那样的话都是0无论如何都该有一个解吧？
我的部队还没到5星，不过这个应该没影响吧？

**Comment by gao462** [comment]
![Untitled](https://user-images.githubusercontent.com/33379471/87202614-e63c8980-c2ce-11ea-8d52-72895e2e1c84.png)

**Comment by xxzl0130** [comment]
设置是指刚好达到目标格数的解  
你都给0那肯定没有啊。。。  
默认就是最优解，使用最优解即可

**Comment by gao462** [comment]
默认值也没解，是因为我芯片数量真的不够吗？
![Untitled](https://user-images.githubusercontent.com/33379471/87446820-cf947c00-c5c7-11ea-851f-d624ef634137.png)
还有能不能AppData下提取芯片的bit array能拿出来到其他网站用吗？能用的话，能说一下吗？我想试试其他的工具。

**Comment by xxzl0130** [comment]
一百多个芯片出不来最优解很正常。  
不过如果你所有的重装都出不了解的话，也许是我程序有问题，可以把那个AppData文件发给我。  
另外可以配合[这个工具](http://bbs.nga.cn/read.php?tid=18401141)使用[乐章的网页版计算器](https://hycdes.com/pages/GFT_ChipCal.html)

**Comment by gao462** [comment]
[User]
Chip="@ByteArray(#H4sIAAAAAAAA/8yd3XIbqRLH30XXuaD5nryMSydWNqo4cY6V7DlVqbz71gBaNQzIoO4Z6W7/2tjWbxroDxrm9+7Tl+OPp/8df355+nU6vD0dv39+3X38vQOhJunm/zo+7z6e5Yf4z8NHRhh5/uDw/x+7jztxli+Hvw8v5w9eX17f4k/M//yvt+NzUtPuw+7031/7Z/znn9OPnb7sfxzSt9nJD/NH+9PpePr59Lz/tv/rkH5d+uzt8PK6n39UXT77cvyZftf5Bw+fn/7zdth/TR8fT08vr5++HgLf7s+HHYjJ2gkxB5kzW8iZrRALbLjKrUw3t6hyiwo3lNyqzi1b3E5l3E7x2toRmVWFWZTMctDWTufMmpdZrzC+F8wNO9eZQWgNyNBJ59QaxqghowZYYXQvqBuzWrepp4L6vXk9Rj0wp+u2hgq1pNlaGufRAp40q60F0da1Eb6gHlrBQYMABB0kJ3P/Qga3T+qhhWxmVDlyOaWJg1sSzdw1uBvMUGd22k0CQUfNunyrbmq1UXgSKFVBTbV1EZxQnVbN1r1Oqx6cBEpTUBuireFWV80/q6+McFtQW15bUwNw/nktpXTgL9RJ38nW9XndRd2Y1/URLo11ONdK+k4BeH2E8wfgM6XWObUuQ3DiCKeGZZQApW1r7QvqxQinhWX987pu61oI3kutmtRG5NSG6q/hVn9dt3XXCB+ztddKIM+VNM3W+QiH/nldp+5Kt4b8daC0BXXpuYjU1BLKCmv4TOkK6sUaTqPuj8MJUcpQkhkofUHN7K+ppaOarTUpDp8pQebUIHnX8P7VjD+1rsdmSmSmjpLV0tTxXVvLejOu+qxWQoHImKH0WsTcur+E0p9lLorBQzG4kiLLt5KmFVEkb5FQE3x1fU4HSl9Ql+N7s3JZfXzXVjJaRUFJ4YXIqL1gjsvsChHKghqGRrhSU0Yd9Z28FqGO0pjXjbVspjQFNbWOcnPNrH+EL1azocxDWacEKv4nzbma9Q9wfuiGqf00WTzAo86hFS21XmF8L6Abs7qxls2QsoAuozKit6bGol1R2dhaNlOagpo5x6Su4LXMmmjrKSsnRMlq6f4IhTC+G7lW3dJaCJhQvSzph9qm59/z0MJJA5g66Iff86DVwbW0E2BbR82aYVIjFP49j0DpCmpqHbyIy/wW1I21rO6stdbaoF29pFlt3U9dzzK7qoQN6npTRqDUBTXzakaNRruyzCG/pa2RuDaa9J2yTIKtG2t4w9YzpSuoy3ldruHSVTrr5HWn3R+o9JcKe9FNA90qmRk86DuFKvVhblYY5lZJV1C/Z/BB6v5NLv5QpeG+rFVK59SqXNJok7t/34Owog3FZ0ZIq1DWlTQnNHU7s6tEOjS+DQDgUkrSdyqRbmZqJ7Kt66RZqfudF2ETd8zWM+VUUJcFJFp4Jvup+5szeitI9bXMODfh9qOkWcOz/u2e/lCcVjezYDTe70ma1W9R2wq7wrNGYaFeIrXgtJCYOmjWFJs6rynJZsvWTuNQPGnWEU4tIvEnIBb8pAymDvpORdL+DZ/eckrL1n7CnitpVmpqC2mNehGPDpVTrFK4MhwlQ9J189QmLGgN8Hq+6YSaAJEnfafawlZ9V056g6tnSbNS99eR+gMV2oGPmVKKnFqWLpu21bXGzO6NxOseO0DKAnrRgHRfU/NvYAdKVVBTT6/dnHXxF0obttZGabyYRc0ana1xqInWThkofUHNnGtSozNKw3DdYztttJky6lmz2po6r1extXYyp3bM7ZSbVIaHtnNnSnyELek7Zdj8zYUNd62NUZBRG1Vu525VLuw/30MrKwRIWUBTa6Q3F876y+G97rphais9zj+SZt3NpXZJrxCkOKXxJkDSrP04j3eCLVC6gpp5557aZlcLzRbnAIaKKV6AxLlH0py2JpeGKWWFFrURHjB10KxByhrdV7SeYQ+AmQGoTuvWHlLCnTBD1SMPuJgQFKeXfrymWQ/45HFQD9WXQWlOqKeWk8T9hEFdn8UW3r/s6OayaH+drPf0Vt3Ok8SnW4K67qessO9Sy1uvtuKfzg1qayTKLKPkHN/9eSV/hlV3VJPNou4o75Rf9S9ipEBMCu/1ZdlOkjUMW6NtlNQiPEOiDuEkWQNu6thmP3grQQp0GDNJ1ooJteuG0hTdYHYGDe2gOEOwTc6Uj+QXUgk9IeIoryPPA6Gk1jyB50YFb6mEQfdZJck6nde4KYK0iyXVNGmBmINkjT6p7WTsTXRSe3Vpv4iKk3iT4w1Dvtla6dB0jpJ1zabuVPLHIx5QF1lU96n19sfZvXWC6qhWQrnLRI7qoUxcI16YeCQUmRkhI14EX0XACUIuoNXVmJNa0u9yUo1YpOqklHKgEXWUnCObenMVJW+u23lmdDky8/K1STV/ZJMuQE4583tZM8ipUi64GoM93p25ylkhL1WSJFlLvP25M/8FN1VfpZzXKCJJkrVeQA3CuhbvkSrvDKllxqyZayRrXKPam2DU7TwZhc5bJsnKTPVX7FfRaeXRefmoWKtC1BWMUs6vemhtpEWtNElyuquBrTn+04bVVXuGRDdgJHmnSlj/yCadVNFGO3Tjd5Kss7k/kySsYENj2wmH7i9K8pFqYezdJIFR5sjMR1Q2uQN6pBKmvURv5YjqvZ2q0f05cjm/KyQZcc8zp8moeQ9W9g9tQk/cyApmlDToJoQkaUMbbo21+5l7jVxn1sJPl+mcJKunol5axJ5MGm0B2znKR+qp6JrLI2FnYPQ5Mm8TN/UK+xpyb1m7iWwhQ7bUeARuPZlBaCQZaS4wVvlL4hzVnfbZ+98eRVuzrTEI2FBdFO/WRZeBhwa1RTuvQbDW/ahLNXuAbSblPFqqo3z0AJs0oi1oh6LNJB8Juauns4FczSms9AqlUUmyBl5r5BQkj2yNdmjjIsnrzKBdJa0wTOD8frlaG3EC0KuTomJPpqjNFOyeeeY0GTVzFZ8actY8M2lSz4w2I+bdcV4jxiYVOh14NKGjum7i8X5W8qUlXeXdoYENXtuMmvlStU1eWDqyz+4Al/CjYk0rqCObUvOrhiTOgPUIOUpWK1M35CgbNfXZbL2aLtsWST7UVg17A68X6GhNEHfasiBcZKDHeBXmZd58XCPm7PVQ1bXaC7CYl/ouqJu7RginIUf2KrzQ6HKOqFhn8CbvoB3xTTOjy4jvdu/MRm/T8EIrgYlV6Zm2KgFt9IKcGREyYOoyDbcu0xs1ZXsQGl28kiSra9rkRY1DE3mG9Dkz87mSh3th4QyJIuskWcNM6i5Fl0seCa09GNzMmeSdet36e3ZJG8teOov9cpR3ms91ZsqqXbezMeJSx46Ktf6zRprcO7LrK5gx6GBcVKzjeo0XM5LSZO9Ao6O9ST5UCkXpH6hb2UEWf0XJykztmWCfy5OS+D0hSbL6Ker18l1bNCOzeTJiQsljkqx2pjKzj+3JSYPOiSXJykx9MUqXbx4pe82QqNSX5EN5qq4ywUisHSBNzsx8SS31VhnmnOpP5duEP/97J0XcxNg//73//unwnAHuv317Pe9RLL5iY2oZW35P52uxRlhC9z+/Pp1+HA7nR/Pp19v8y5LKhv3l4wt9fNgx4385fg6jxc4u+Nvb4fy93/bfz3uTp6/Hlxc4/4+gZKbULrsuJl3NbKSIO5Lx03/tHeX5eVkRz8rHIGj4cdpWYW9hdlMbHJbtaUKI2/59msD/NL2F4mmq1tM08Ua3a0/T1h5mK4yzi0AAVG10KrbHacKO/PlxBn8SH6fneZpaal88Tag+zT9//gkAAP//MM7yfnOSAAA=\n)"
Solutions=@ByteArray([])

**Comment by xxzl0130** [comment]
测试过了，程序没问题，你把自由格数调大就能出解，确实是芯片太少的原因
