### ISSUE TITLE
无法获取芯片数据

### ISSUE THREAD

**Issue by Liyulive** [xxzl0130/CodeX#6]
都提示网络错误，本地代理code2，网络代理code99.
设备Android11 Havoc, 电脑Win11

**Comment by xxzl0130** [comment]
参考[这里面的FAQ](https://bbs.nga.cn/read.php?tid=20284990)

**Comment by Liyulive** [comment]
看过了，后来把电脑上所有可能的情况筛选了一遍解决了，关掉MFile就好了。也不知道为什么，以前win10的时候没事，升到win11之后就不行了。
