### ISSUE TITLE
利用find()取代operator[]

### ISSUE THREAD

**Issue by woofsauce** [xxzl0130/CodeX#8]
你好

我把AltSolutionWindow::chipUsed裡面的operator[]改成了find()，並把chipCount_改成了unordered_map發現有些微的效能提升
測試設定為8線程，計算1000000個AGS-30方案
(不太準確的)測試結果如下:
未改動: 2.07~2.30秒
find(): 1.53~1.67秒
find()+unordered_map: 1.40~1.53秒

請問這樣的改變可行嗎:
https://github.com/woofsauce/CodeX/commit/05fb95bacfc3777456a54084b38ab0feec430e25

不過除了要算出極限能力值以外大概也沒多少人會算那麼多方案吧

**Comment by xxzl0130** [comment]
* find的改动会避免在没有值的时候插入新值，operator[]是会在key不存在的时候直接创建一组key value的  
* unordered_map是基于hash的O(1)的操作，对于int来说确实是会快一些  
提升了25%也不小了，下次更新我会合入

**Comment by woofsauce** [comment]
試著把MSVC的選項也改了一改，結果更快了一些
不過測試的時候有一次明明開始了計算，但是下面的方案數卻沒有變化，也不知道是哪邊出了問題。

測試方法還是用AGS-30計算1000000和3000000個方案

未改動:
2.62-2.85秒

只在Chip/ChipSolver上啟用/GL:
2.52-2.62秒

Codex project linker啟用/LTCG，全部project啟用/GL:
2.29-2.40秒
6.95-7.11秒 (3000000個方案)

接下來是更進一步，但是感覺上不太有意義的改動。在Ivy Bridge上好像能快一點，可能要看看counter才會知道原因了…不過也有可能只是測試時的偏差
ChipSolver::startSolve()內百分比計算改成float和powerf():
2.08-2.18秒
6.77-7.11秒 (3000000個方案)

chip.cpp內double也改成float: 
6.45~6.89秒

git diff:
https://gist.github.com/woofsauce/c0922c3d87cf427722a0248a7471a7be

另外也試著加上unordered_map和find()跑了幾輪三千萬個方案，花費時間大概是未改動前的60%
