### ISSUE TITLE
支持非GB2312環境下編譯和以Clang編譯

### ISSUE THREAD

**Issue by woofsauce** [xxzl0130/CodeX#9]
根據測試結果來看，目前似乎沒有在辦法不改動C++文件內中文字串的前提下改由Clang編譯。從[P2295R5](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p2295r5.pdf)和Clang[相關文檔](https://releases.llvm.org/13.0.0/tools/clang/docs/UsersManual.html#id9)中得出，Clang目前好像只能支持UTF-8。

MSVC在系統預設為Windows-1252編碼的環境下也會出現編譯後執行檔內中文顯示失常的問題(下圖一)，雖然說 “/source-charset: gb2312” 編譯選項可以改善此問題，但是Visual Studio似乎仍然沒辦法自動判斷文件編碼種類(下圖二)。

![image](https://user-images.githubusercontent.com/46232230/155927961-e40e24d2-7874-47b2-9e39-ed49a81b2549.png)
圖一: 在Windows-1252下直接以MSVC編譯後成果

![image](https://user-images.githubusercontent.com/46232230/155928045-7f03bdda-7412-4d36-961d-c77dbf1f784e.png)
圖二: Chip.cpp在Windows-1252編碼環境下以Visual Studio 2022直接開啟後成果

因此想請問能否把C++文件編碼改為UTF-8-BOM。改動後在Windows-1252和GB2312環境下MSVC/Clang都可以直接編譯，Visual Studio也可以不做任何調整就直接正常顯示中文。

另外不知是否我這邊Qt環境上的差異，ChipSolver.cpp以及Chip.cpp內需要另外添加  "#include \<QFile\>" 才可以編譯。

改動如下，我也可以開一個PR:
https://github.com/woofsauce/CodeX/commit/4b9c7a10fc7f214b61c83dcf09697ed91dc85845

謝謝

**Comment by xxzl0130** [comment]
最新版本已改为UTF-8 with bom
